### ISSUE TITLE
Can't use "this" inside onSelect event action

### ISSUE THREAD

**Issue by OPADA-Eng** [moayadnajd/nativescript-filter-select#1]
Hi Moayad,
I'm using your brilliant plugin and it's very helpful, but when I use onSelect event I can't reach to the view model of the context, My code bellow:
>`<FS:FilterSelect col="1"
                                             class="p-15"
                                             visibility="{{ customer_type   == 1 ? 'visible' : 'collapsed' }}"
                                             items="{{ customer_areas }}"
                                             hint="Please select a customer"
                                             modal_title="Customers" search_param="name"
                                             primary_key="customer_area_id"
                                             onSelect="{{ onSelectCustomerArea }}"
                                             selected="{{ selected_customer_area_obj }}"
                                    />`

`public onSelectCustomerArea(selected){
        console.log(this);
    }`

this return: 

> "FilterSelect(1551)@file:///.." filter select xml file

Can you help ?
Thanks

**Comment by moayadnajd** [comment]
hi @OPADA-Eng 
you can use self in second param  temporary until i found something better 

public onSelect(selectedArray,slef) {
    console.log('selected array is => ' + JSON.stringify(selectedArray));
    console.log('selected array is => ' + JSON.stringify(slef.selected));
  }

**Comment by dyazincahya** [comment]
How to send data from variable "selectedArray" in "model" to "controller" ?

**Comment by moayadnajd** [comment]
@dyazincahya can you open new issue with repo example so we can help you

**Comment by moayadnajd** [comment]
@OPADA-Eng  now the change event is there no need to this method please see demo for more information
