### ISSUE TITLE
Is possible to use a font awesome icon as the select trigger?

### ISSUE THREAD

**Issue by leocrawf** [moayadnajd/nativescript-filter-select#16]
Is possible to use a font awesome icon as the select trigger?

**Comment by moayadnajd** [comment]
@leocrawf thank you for this idea i will work on it and get back to you with update thanks

**Comment by moayadnajd** [comment]
@leocrawf  you can do like this now  hint="{{'fa-list-ul' | fonticon}}"

**Comment by leocrawf** [comment]
Nice. Thank you.

**Comment by giulianimartini** [comment]
Hi @moayadnajd,

is it possible to use fonticon at the `btn-filter-select` (`selectText` property)?
I was wondering to use an icon like search from fontawesome.

And how about change the style of `clearText` and `closeText`? On Android they have shadow and border that I want to remove, but I can't.

Thanks

**Comment by giulianimartini** [comment]
I achieved the first issue about the `selectText` icon, but I'm still stucked with the `clearText` and `closeText` issue.

Can someone help me?

Thanks in advance.
