### ISSUE TITLE
Doesn't run properly using nativescript-webpack

### ISSUE THREAD

**Issue by xliank** [moayadnajd/nativescript-filter-select#18]
When i'm using default command "tns run android", it work nice. but when i'm switch to nativescript-webpack command, it won't work:

1. I'm using nativescript template "tns-template-hello-world-ng"
2. I'm also using"nativescript-webpack" with command "npm run start-android-bundle"
3. When i'm click on "select" button, it show error 

`
System.err: com.tns.NativeScriptException:
System.err: Calling js method getView failed
System.err: Error: Parsing XML at 1:1
System.err:  > Module 'ui/label' not found for element 'Label'.
System.err:    > com.tns.NativeScriptException: Failed to find module: "ui/label", relative to: app/tns_modules/
System.err:       com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     com.tns.Module.resolvePath(Module.java:55)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:953)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:937)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:929)
System.err:     com.tns.gen.android.widget.BaseAdapter_frnal_ts_helpers_l58_c38__ListViewAdapter.getView(BaseAdapter_frnal_ts_helpers_l58_c38__ListViewAdapter.java:47)
System.err:     android.widget.AbsListView.obtainView(AbsListView.java:2349)
System.err:     android.widget.ListView.makeAndAddView(ListView.java:1864)
System.err:     android.widget.ListView.fillDown(ListView.java:698)
System.err:     android.widget.ListView.fillFromTop(ListView.java:759)
System.err:     android.widget.ListView.layoutChildren(ListView.java:1673)
System.err:     android.widget.AbsListView.onLayout(AbsListView.java:2153)
System.err:     android.view.View.layout(View.java:15686)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5039)
System.err:     org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:169)
System.err:     org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:123)
System.err:     android.view.View.layout(View.java:15686)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5039)
System.err:     org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
System.err:     android.view.View.layout(View.java:15686)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5039)
System.err:     android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
System.err:     android.widget.FrameLayout.onLayout(FrameLayout.java:514)
System.err:     android.view.View.layout(View.java:15686)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5039)
System.err:     android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
System.err:     android.widget.FrameLayout.onLayout(FrameLayout.java:514)
System.err:     android.view.View.layout(View.java:15686)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5039)
System.err:     android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
System.err:     android.widget.FrameLayout.onLayout(FrameLayout.java:514)
System.err:     android.view.View.layout(View.java:15686)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5039)
System.err:     android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
System.err:     android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
System.err:     android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
System.err:     android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
System.err:     android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
System.err:     android.view.Choreographer.doCallbacks(Choreographer.java:580)
System.err:     android.view.Choreographer.doFrame(Choreographer.java:550)
System.err:     android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
System.err:     android.os.Handler.handleCallback(Handler.java:739)
System.err:     android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     android.os.Looper.loop(Looper.java:135)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5294)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     java.lang.reflect.Method.invoke(Method.java:372)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
System.err: File: "file:///data/data/com.app.name/files/app/vendor.js, line: 50597, column: 20
System.err: StackTrace:
System.err:     Frame: function:'ScopeError', file:'file:///data/data/com.app.name/files/app/vendor.js', line: 49536, column: 24
System.err:     Frame: function:'PositionErrorFormat', file:'file:///data/data/com.app.name/files/app/vendor.js', line: 50610, column: 16
System.err:     Frame: function:'', file:'file:///data/data/com.app.name/files/app/vendor.js', line: 50597, column: 33
System.err:     Frame: function:'', file:'file:///data/data/com.app.name/files/app/vendor.js', line: 75143, column: 13
System.err:     Frame: function:'module.exports.EasySAXParser.parse', file:'file:///data/data/com.app.name/files/app/vendor.js', line: 76011, column: 23
System.err:     Frame: function:'module.exports.XmlParser.parse', file:'file:///data/data/com.app.name/files/app/vendor.js', line: 75190, column: 22
System.err:     Frame: function:'module.exports.XmlStringParser.parse', file:'file:///data/data/com.app.name/files/app/vendor.js', line: 50603, column: 27
System.err:     Frame: function:'parseInternal', file:'file:///data/data/com.app.name/files/app/vendor.js', line: 50448, column: 11
System.err:     Frame: function:'parse', file:'file:///data/data/com.app.name/files/app/vendor.js', line: 50426, column: 31
System.err:     Frame: function:'createView', file:'file:///data/data/com.app.name/files/app/vendor.js', line: 64807, column: 38
System.err:     Frame: function:'ListViewAdapter.getView',file:'file:///data/data/com.app.name/files/app/vendor.js', line: 64719, column: 33
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:953)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:937)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:929)
System.err:     at com.tns.gen.android.widget.BaseAdapter_frnal_ts_helpers_l58_c38__ListViewAdapter.getView(BaseAdapter_frnal_ts_helpers_l58_c38__ListViewAdapter.java:47)
System.err:     at android.widget.AbsListView.obtainView(AbsListView.java:2349)
System.err:     at android.widget.ListView.makeAndAddView(ListView.java:1864)
System.err:     at android.widget.ListView.fillDown(ListView.java:698)
System.err:     at android.widget.ListView.fillFromTop(ListView.java:759)
System.err:     at android.widget.ListView.layoutChildren(ListView.java:1673)
System.err:     at android.widget.AbsListView.onLayout(AbsListView.java:2153)
System.err:     at android.view.View.layout(View.java:15686)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5039)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:169)
System.err:     at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:123)
System.err:     at android.view.View.layout(View.java:15686)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5039)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
System.err:     at android.view.View.layout(View.java:15686)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5039)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
System.err:     at android.view.View.layout(View.java:15686)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5039)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
System.err:     at android.view.View.layout(View.java:15686)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5039)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
System.err:     at android.view.View.layout(View.java:15686)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5039)
System.err:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:580)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:550)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
System.err:     at android.os.Handler.handleCallback(Handler.java:739)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:135)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5294)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
ActivityManager: Process com.app.name (pid 30944) has died
ActivityManager: cleanUpApplicationRecord -- 30944`

**Comment by moayadnajd** [comment]
@xliank thank you for your help i actually not test it with web pack can you provide demo repo so u can test on it and fix this for you

**Comment by xliank** [comment]
@moayadnajd sure, here it is https://github.com/xliank/NSFilterWebpack
command "npm run start-android-bundle" and "tns run android"

**Comment by xliank** [comment]
@moayadnajd  I found on other project that you need to exclude in uglify mangle
example https://github.com/PeterStaev/NativeScript-Drop-Down/blob/master/uglify-mangle-excludes.ts
But i don't really understand what the arrays mean for.
somebody please?

**Comment by anuragd7** [comment]
Hi 
The plugin seems great, however I wanted to check if it works with webpack as I need to use webpack in my project. Is this issue sorted out?
Thanks

**Comment by moayadnajd** [comment]
@anuragd7 the problem is i don't have experience in webpack so i have hard time to debug  but i will try to fix this soon

**Comment by anuragd7** [comment]
Thanks for the prompt response @moayadnajd !

**Comment by moayadnajd** [comment]
@anuragd7  i just try new installation and everything work fine with webpack i will share demo with you now

**Comment by moayadnajd** [comment]
@xliank i don't know why your example not working but i try new one its working fine

**Comment by moayadnajd** [comment]
@anuragd7 and @xliank  please check https://github.com/moayadnajd/nativescript-filter-select/tree/master/demo-webpack 
the plugin working with webpack fine

**Comment by kmuthukrishnan** [comment]
Thanks @moayadnajd .Trying it out now!

**Comment by bachras** [comment]
@xliank Did you manage to solve the issue on Angular as example @moayadnajd provided non-Angular  solution. Do you have any suggestions? This is the only thing stopping me from publishing the app...

**Comment by bachras** [comment]
@anuragd7 Thanks for prompt reply. I am having same issue as @xliank had, I also opened an issue https://github.com/moayadnajd/nativescript-filter-select/issues/43 . Did you make any changes to webpack configuration? If so, could you share config file or code snippet where you made changes? Thank you very much.

**Comment by anuragd7** [comment]
Have posted my response in  #43
<https://github.com/moayadnajd/nativescript-filter-select/issues/43> .
Hope it works for you

**Comment by xliank** [comment]
@bachras no, i consider Angular with Nativescript is too much for me & too many breaking changes in Nativescript.

 So i’m moving to React Native. 

Even at first it was hard, but it’s worth it. more freedom, close to vanilla js,es6, faster bootup speed, image cache out of box, redux even great.
