### ISSUE TITLE
Multi select item generate design issues

### ISSUE THREAD

**Issue by nikunjgajera** [moayadnajd/nativescript-filter-select#20]
I am create native android application using nativescript. I have required multi items from dropdown so i found this plugin but when i using this plugin and select multiple items from list so i got design issues.

page.html
```
<StackLayout horizontalAlignment="center">
                <FilterSelect 
                    height="100%"
                    [items]="players"
                    (change)="onitemselected($event)"
                    hint="Please select some players" 
                    modal_title="Player" search_param="name" 
                    primary_key="id">
                </FilterSelect>
            </StackLayout>
```

page.component.ts
```

export class PageComponent implements OnInit{
    players: Array<Object> = [];
    ngOnInit() {
         this.players.push({ name: 'Player 1', id: 1});
        this.players.push({ name: 'Player 2', id: 2});
        this.players.push({ name: 'Player 3', id: 3});
        this.players.push({ name: 'Player 4', id: 4});
        this.players.push({ name: 'Player 5', id: 5});
        this.players.push({ name: 'Player 6', id: 6});
        this.players.push({ name: 'Player 7', id: 7});
        this.players.push({ name: 'Player 8', id: 8});
        this.players.push({ name: 'Player 9', id: 9});
        this.players.push({ name: 'Player 10', id: 10});
    }
}
```

When page load at a time no any item selected. see below screen
![selection_005](https://user-images.githubusercontent.com/12508078/33513921-7f455320-d770-11e7-93e4-6f03befab0c5.png)

Selection Screen where i put 10 players manually, 
![selection_006](https://user-images.githubusercontent.com/12508078/33513922-915b1fa4-d770-11e7-9d5f-0ce6b1fcc93b.png)

When i selected all players so all players are display in mail screen like below
![selection_007](https://user-images.githubusercontent.com/12508078/33513928-9f08cb24-d770-11e7-9e64-ab92f1fef714.png)

so how to solved mail page design?

**Comment by moayadnajd** [comment]
@nikunjgajera hey thanks for mention this can you share with me your repo or attach code example so we can work together on this

**Comment by moayadnajd** [comment]
@nikunjgajera and also did you include the css files !!??

**Comment by nikunjgajera** [comment]
@moayadnajd i included css file but still getting design issues.

**Comment by nikunjgajera** [comment]
Please check this source code,
You need to add platform by `tns platform add android`
then run `tns run android`
and see design issue and how to solve this design issue.
[Demo.zip](https://github.com/moayadnajd/nativescript-filter-select/files/1542925/Demo.zip)

**Comment by moayadnajd** [comment]
@nikunjgajera the css was not imported good and i don't have android emulator so i made some changes and run it in iOS seems everything fine so  please let me know 

[Demo-edited.zip](https://github.com/moayadnajd/nativescript-filter-select/files/1544823/Demo-edited.zip)

**Comment by nikunjgajera** [comment]
@moayadnajd thank for solved issue, but can you tell me which css have you modified. i cant find it
