### ISSUE TITLE
Changing labels

### ISSUE THREAD

**Issue by VChabrette** [moayadnajd/nativescript-filter-select#21]
Hi !

Firstly, thanks for your awesome plugin, it really works like a charm !

However, I have some concerns about the "Select", "Close" and "Clear" labels. 
As I'm working for a French company, I have to translate thoses labels, but I can't see any way I could do it without modifying the plugin and removing the harcoded strings.

Do you have any idea if I could do this without modifying the plugin ?

Thanks in advance !

**Comment by moayadnajd** [comment]
Hey @VChabrette actually its good idea i made this please update to v 1.2.1
you can do like below i translate it to Arabic so you can do French 💃  let me know if you need anything  and don't forget to start the plugin ⭐️  

`  <FS:FilterSelect  items="{{ countries }}" closeText="إغلاق" searchHint="بحث" doneText="تم" clearText="مسح" selectText="إختر" hint="اختر الدوله" modal_title="الدول" search_param="name" primary_key="code"  change="{{ onSelect }}"  />`

**Comment by VChabrette** [comment]
Hi @moayadnajd ! Thanks for the update, it's working like a charm !
Thanks a lot for you reactiveness too :smiley: I'm starring your project with great pleasure :wink: 

However, something I didn't mention in the first place is the fact that the "Clear"/"Close" labels wrap and give a weird look to the interface ([screenshot](https://user-images.githubusercontent.com/3647132/33829835-1c944f3e-de72-11e7-8a43-a1f273845eec.png)). Have you any idea why I'm experiencing this issue ?
PS: I can open a new issue mentionning that if you want, I just didn't want to look like the type of guy who would burry you under tons of issues haha

**Comment by moayadnajd** [comment]
@VChabrette thank man and yes please open new issue because this is critical
