### ISSUE TITLE
Modal button texts wrap unexpectedly 

### ISSUE THREAD

**Issue by VChabrette** [moayadnajd/nativescript-filter-select#23]
Hi !

As I was mentionning in my last [issue](https://github.com/moayadnajd/nativescript-filter-select/issues/21), I'm having trouble with the modal buttons' texts which wrap unexpectedly => [screenshot](https://user-images.githubusercontent.com/3647132/33829835-1c944f3e-de72-11e7-8a43-a1f273845eec.png)

FYI I'm using a Samsung Galaxy A5 to test my application, at a 720 x 1280 pixels resolution with a ~294 ppi density (according to [GsmArena](https://www.gsmarena.com/samsung_galaxy_a5-6761.php))

**Comment by moayadnajd** [comment]
@VChabrette please update and let me know if it still come up

**Comment by VChabrette** [comment]
@moayadnajd It's perfect, no more wrap, thanks a lot :smile:
