### ISSUE TITLE
Unable to style some element attributes through css classes

### ISSUE THREAD

**Issue by anuragd7** [moayadnajd/nativescript-filter-select#24]
Hi 
Thanks for this plugin, its very useful. I ran into some styling issues when trying it out.

In am unable to style the component using the provided css classes. These are the styles that I am not able to apply 

1.  font size of the selected tags by specifying a font size in the `.filter-select-tag label` class
2. width of the delete tag button by specifying a width in the `.filter-select-tag-delete ` class

This behaviour can be observed by cloning the ng-demo app and occurs in android and also ios.

**Comment by moayadnajd** [comment]
please make playground like this so we can edit and see togather 
https://play.nativescript.org/?template=play-tsc&id=gDKleZ

**Comment by moayadnajd** [comment]
@anuragd7  please try now  i made some changes maybe now it fixed

**Comment by anuragd7** [comment]
Hi @moayadnajd 
Just tried version 1.2.2 and can confirm that I am now able to apply font-size and width styles using css. 
Thank you for your help.
