### ISSUE TITLE
Question - Programatically pushing new values into the selected tags

### ISSUE THREAD

**Issue by kmuthukrishnan** [moayadnajd/nativescript-filter-select#26]
Hi @moayadnajd , 

I am using your component (thanks!) for selecting tags from a large list of tag items. I also allowing users to create their own tag items. I am trying to push these programatically into the filter-select-component. When I do this, the value of nativelement.tags is correctly getting incremented (I can console.log this), but the view does not change. Its only when I reload the UI by going into the filter and tap "done" does the view change and the tags added by the user become visible. Please help me understand:

a. How can I refresh the view to show the programatically added tags without going into the filter component? I have tried running this is ngZone with no luck. 
b. Can the refresh method help me with this?

Thanks

**Comment by moayadnajd** [comment]
@kmuthukrishnan 
please check this playground you can use the refresh method 

and i will add feature to add your tag if not exist and remote data url soon  

 https://play.nativescript.org/?template=play-tsc&id=gDKleZ

**Comment by kmuthukrishnan** [comment]
Hi @moayadnajd ,
Thanks, Iam trying the refresh method - it seems to be working. 
Do let me know when you create the add you tag and remote data url features! Waiting for it :)
