### ISSUE TITLE
Open keyboard on "Select" click

### ISSUE THREAD

**Issue by NickB95** [moayadnajd/nativescript-filter-select#27]
Is it possible to open the keyboard on both OS when Select is clicked?

I've tried focus'ing the searchBar but that doesn't seem to work.

**Comment by NickB95** [comment]
Typical, I spend hours trying to do this, ask for help, then immediately solve it myself!

I simply added a call to the focus event for the search bar in the common.ts file just under the creation of the SearchBar.

**Comment by VChabrette** [comment]
Hi @NickB95,

Actually, I'm quite surprised by your issue, because, in fact, in my app, the keyboard is displayed as soon as the modal opens itself and I would like to disable this. 
So, in fact, I have the total opposite of your issue haha

Maybe it would be a nice addition to give the possibilty to choose to autofocus or not ? @moayadnajd

**Comment by moayadnajd** [comment]
@NickB95  can you please share your code with me 
@VChabrette yes maybe this can be good idea
i will try to work on that soon but as you know its hard to find free time

**Comment by moayadnajd** [comment]
@VChabrette i think the keyboard open up just in android is that right ??
@NickB95 are you working in iOS or both ?

**Comment by VChabrette** [comment]
@moayadnajd Haha, yeah, I know free time is hard to find, I'm having the same struggle for my personal projects
And yes, I admit I have not tested this on iOS, I'm working on an Android-only app :confused:

**Comment by moayadnajd** [comment]
@VChabrette and @NickB95  please update to latest and put autofocus="false Or True" to hide or show the keyboard when modal showing

**Comment by VChabrette** [comment]
Hey @moayadnajd ! Sorry, I was on vacation, but I just tried it and it's working like a charm ! Thanks for this functionnality :smile:

**Comment by VChabrette** [comment]
@moayadnajd However, it seems like you forgot to remove the console.log('->>>>>>>>>>this.modalPage.on("loaded", function(args)'); haha

**Comment by moayadnajd** [comment]
@VChabrette hahah thanks i will do that
