### ISSUE TITLE
ObseraveblArray

### ISSUE THREAD

**Issue by LorenDorez** [moayadnajd/nativescript-filter-select#29]
I am setting up a Cascading Affect.

For Example:
I have one filter-select item for type and when someone chooses a value it then runs an API call and downloads a new list of categories i update the categories on the viewModel but this never updates the 2nd filter-select until i manually update the .items property

```
console.dir(categories[0]);
                                const pv = viewModel.page.getViewById("propertyv");
                                //pv.items = viewModel.dataSources.categories;
                                pv.refresh();
```

**Comment by moayadnajd** [comment]
@LorenDorez  can you show me an example 
maybe on play.nativescript.org

**Comment by moayadnajd** [comment]
@LorenDorez  did you try the refresh() method ??

**Comment by LorenDorez** [comment]
@moayadnajd using the same concept from this issue #26 

Look here, it doesnt work unless i reset the items array

https://play.nativescript.org/?template=play-tsc&id=gDKleZ&v=3

**Comment by moayadnajd** [comment]
@LorenDorez the modal take what inside the items array when you tap on select so you can't add when the modal open but why you need to add new item when the modal open i made dependant selection previously with FilterSelect and its fine like this example below  you can add items without refresh or hard reset the items  and you can disable or hide until user make first selection 
https://play.nativescript.org/?template=play-tsc&id=gDKleZ&v=4

**Comment by LorenDorez** [comment]
@moayadnajd 
Sorry thats was abad example. Im not using the same Modal. Ill try to create you a sample project just dont have the free time need to look for another solution.

I basically load the Items of the second Filter based on what they choose on the first filter

**Comment by moayadnajd** [comment]
@LorenDorez i will close this until you gave me is this a future request or its a bug and let me know what should i do
