### ISSUE TITLE
Binding value from control to model

### ISSUE THREAD

**Issue by PeterStaev** [moayadnajd/nativescript-filter-select#30]
I'm recently using your plugin in an app and seems when the user changes the selection (I'm using it in `label` mode, so single select) the change is not persisted to the model. Bindings seem to be correct as the initial value is populating fine. Also if I log the plugin's `selected` property it shows the updated value.

**Comment by moayadnajd** [comment]
@PeterStaev  can you provide example line this 
https://play.nativescript.org/?template=play-tsc&id=gDKleZ&v=3

**Comment by moayadnajd** [comment]
@PeterStaev sorry for delay i was in vacation

**Comment by PeterStaev** [comment]
Here is a playground example: https://play.nativescript.org/?template=play-tsc&id=gDKleZ&v=6
Select a country, then tap the button - the bound property in the model will have length of 0 while the `selected` property of the control has length 1.

**Comment by moayadnajd** [comment]
@PeterStaev  i just update the plugin to fix this issue see example  and update your project  to 1.2.5

https://play.nativescript.org/?template=play-tsc&id=gDKleZ&v=7
