### ISSUE TITLE
Trigger change event on selection clear

### ISSUE THREAD

**Issue by PeterStaev** [moayadnajd/nativescript-filter-select#31]
Would be really nice to trigger the `change` event on selection clear as now there is no way to detect if the user  cleared the selection. Or may be even better to add a separate event for this.

**Comment by moayadnajd** [comment]
@PeterStaev yes maybe thats a good idea i will do it soon

**Comment by moayadnajd** [comment]
@PeterStaev and sorry for delay i was in vacation

**Comment by moayadnajd** [comment]
@PeterStaev  i just update the plugin to fix this issue update your project  to 1.2.5
