### ISSUE TITLE
Modal Popup overwriting styled ActionBar

### ISSUE THREAD

**Issue by tylerablake** [moayadnajd/nativescript-filter-select#32]
I have a blue ActionBar with white text, and when the modal pops up it overwrites the ActionBar to be white with I'm assuming white text. Any help would be appreciated! Thanks!

![image](https://user-images.githubusercontent.com/10442416/36599348-1c49e4ea-187d-11e8-9897-3738faf4600f.png)

**Comment by tylerablake** [comment]
Adding this css gave these results.


![image](https://user-images.githubusercontent.com/10442416/36600938-c09470ac-1881-11e8-856b-f6b1d40b91c4.png)



![image](https://user-images.githubusercontent.com/10442416/36600928-b42dd178-1881-11e8-9df5-cf27933fcca7.png)

**Comment by moayadnajd** [comment]
@tylerablake can you provide example like this https://play.nativescript.org/?template=play-tsc&id=gDKleZ&v=7
so I can edit on it

**Comment by tylerablake** [comment]
@moayadnajd  Thanks for looking into this! I couldn't get that sample to run on my phone. I'll try and get something uploaded and let you take a look at it.

**Comment by moayadnajd** [comment]
@tylerablake sorry i will close this until you provide more info
