### ISSUE TITLE
filter-select problem with scrollview

### ISSUE THREAD

**Issue by ejaz** [moayadnajd/nativescript-filter-select#33]
we are facing problem with filter-select when placed in scrollview. Please have a look at the playground app below.

https://play.nativescript.org/?template=play-js&id=Sbhmtj&v=8

if we remove the scrollview tags, the filter-select works fine. see below for working demo

https://play.nativescript.org/?template=play-js&id=Sbhmtj&v=7

**Comment by moayadnajd** [comment]
@ejaz are you working with android ?? because everything fine on iOS i will see on android and let you know

**Comment by ejaz** [comment]
yes we are working with android

**Comment by ejaz** [comment]
we have found the issue. it was in our CSS.
