### ISSUE TITLE
Clear function 

### ISSUE THREAD

**Issue by ahtishamashraf** [moayadnajd/nativescript-filter-select#34]
Hi , is there any function that could reset everything and show Hint when run in the Script?
I studied the Plugin and saw that Clear in the Modal can work for me , is there any way to run it by including it in Script?

**Comment by moayadnajd** [comment]
@ahtishamashraf  i will add this feature for you

**Comment by ahtishamashraf** [comment]
Can I know when this will be available?

**Comment by moayadnajd** [comment]
@ahtishamashraf today working on it

**Comment by ahtishamashraf** [comment]
I will be thankful to you if you release it ASAP

**Comment by moayadnajd** [comment]
@ahtishamashraf please update to 1.2.6 

then you can do  

```
 let myFilterSelectToClear = <any>this.page.getViewById('myFilterSelectToClear');
    myFilterSelectToClear.Clear();
```

don't forget to star the plugin 👍 😄

**Comment by ahtishamashraf** [comment]
Thanks a Lot Starring the Plugin

**Comment by ahtishamashraf** [comment]
Hi , One More issue I need to ask , I have 2 Filter Select Dropdown in my Page and I want to check if there are 2 options selected and need to decide the 2nd Dropdown based on the First one , if 1st one has 2 Options the render will change to drop and if 1 option is selected render will be tag.
I used viewModal.set("render","tag") if there is 1 option and  viewModal.set("render","drop") if 2 options , and render has render={{ render }} in the xml , now changing the first dropdown isn't changing the behaviour of second

**Comment by moayadnajd** [comment]
you  have to see the refresh() function after you change things just use refresh function and if it not working please make example like this one https://play.nativescript.org/?template=play-tsc&id=gDKleZ&v=3
and open new issue thanks

**Comment by ahtishamashraf** [comment]
Hi , It would be helpful if you provide me a playground where you have implemented this code 
` let myFilterSelectToClear = <any>this.page.getViewById('myFilterSelectToClear');
    myFilterSelectToClear.Clear();`

**Comment by moayadnajd** [comment]
@ahtishamashraf you can see in the demo how i made this working and you can see the clear button

**Comment by ahtishamashraf** [comment]
I have created the app in js , so if I get the relative js code it would be helpful
