### ISSUE TITLE
Is there a way to access the close modal event?

### ISSUE THREAD

**Issue by leocrawf** [moayadnajd/nativescript-filter-select#39]
Is there a way to access the close button event?

**Comment by moayadnajd** [comment]
@leocrawf for now no but i will do it soon for you

**Comment by moayadnajd** [comment]
@leocrawf i just updated the plugin to v 1.2.7 and your issue is solved there 

you can do like  below 

in view model
```
public closeModal(args){
    console.log('on close selected array is => ' + JSON.stringify(args.selected));
  }
```

in xml 

`<FS:FilterSelect close="{{ closeModal }}"  />`

see demo for running example and don't forget to star the plugin 😄 ⭐️

**Comment by leocrawf** [comment]
Thank you.
