### ISSUE TITLE
Angular Version

### ISSUE THREAD

**Issue by crazycoder775** [moayadnajd/nativescript-filter-select#4]
Hi, 

the plugin looks fine but how can I run it with the Angular version of Nativescript ?

The XML tags at the top of page are not supported with Angular version.

**Comment by moayadnajd** [comment]
@crazycoder775  iam sorry for the late response i was too busy i think you can do something like 
this but i did not try it i use typescript in development when i have time i will gave it a try and get back to you please if you try let me know  

```
import * as elementRegistryModule from 'nativescript-angular/element-registry';
elementRegistryModule.registerElement("FilterSelect", () => require("nativescript-filter-select"). FilterSelect);
```

```
<FilterSelect 
     items="{{ countries }}"
     hint="Please select some countries" 
     modal_title="Countries" search_param="name" 
     primary_key="code" 
     onSelect="{{ onSelect }}"
 />
```

**Comment by moayadnajd** [comment]
@crazycoder775 i just added angular support you van see demo-ng folder feel free to open new issue
