### ISSUE TITLE
Plugin is not compatible with {N} v4

### ISSUE THREAD

**Issue by OPADA-Eng** [moayadnajd/nativescript-filter-select#40]
Hi @moayadnajd 
This plugin showing an Error after updating to v4.0.1 of nativescript
This is the error message: 

> JavaScript error:
file:///app/tns_modules/tns-core-modules/ui/builder/builder.js:238:56: JS ERROR Error: Building UI from XML. @file:///app/main-page.xml:12:6
> Module '/Users/myuser/Library/Developer/CoreSimulator/Devices/7E165C3A-58FA-4E95-9742-10FA73F7FD34/data/Containers/Bundle/Application/071D5890-9E81-4718-B3A0-CDD9CE89E0FC/demo.app/app/nativescript-filter-select' not found for element 'nativescript-filter-select:FilterSelect'.
> Could not find module '/Users/myuser/Library/Developer/CoreSimulator/Devices/7E165C3A-58FA-4E95-9742-10FA73F7FD34/data/Containers/Bundle/Application/071D5890-9E81-4718-B3A0-CDD9CE89E0FC/demo.app/app/nativescript-filter-select'. Computed path '/Users/myuser/Library/Developer/CoreSimulator/Devices/7E165C3A-58FA-4E95-9742-10FA73F7FD34/data/Containers/Bundle/Application/071D5890-9E81-4718-B3A0-CDD9CE89E0FC/demo.app/app/nativescript-filter-select'.

tns runtime :
```
    "tns-ios": {
      "version": "4.0.1"
    },
    "tns-android": {
      "version": "4.0.1"
    }
```
tns core modules: 
```
"dependencies": {
    "nativescript-filter-select": "^1.2.7",
    "nativescript-fonticon": "^1.1.1",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-unit-test-runner": "^0.3.4",
    "nativescript-web-image-cache": "^4.2.2",
    "tns-core-modules": "^4.0.0"
  }
```
any solution for that ?
Thanks.

**Comment by moayadnajd** [comment]
@OPADA-Eng  please update to latest 

see this example https://play.nativescript.org/?template=play-tsc&id=ofch6A&v=9

**Comment by OPADA-Eng** [comment]
Thanks Man!
