### ISSUE TITLE
not working in angular 5 version.

### ISSUE THREAD

**Issue by muthukumaroptisol** [moayadnajd/nativescript-filter-select#41]
My version is below

"dependencies": {
        "@angular/animations": "^5.2.0",
        "@angular/common": "^5.2.0",
        "@angular/compiler": "^5.2.0",
        "@angular/core": "^5.2.0",
        "@angular/forms": "^5.2.0",
        "@angular/http": "^5.2.0",
        "@angular/platform-browser": "^5.2.0",
        "@angular/platform-browser-dynamic": "^5.2.0",
        "@angular/router": "^5.2.0",
        "@ngx-translate/core": "^9.1.1",
        "@ngx-translate/http-loader": "2.0.1",
        "core-js": "^2.4.1",
        "rxjs": "^5.5.2",
        "zone.js": "^0.8.14"
    },

I am using angular 5 version, As per the document this npm has been installed then it is showing empty page (no error also). Your demo version does run well since Angular version is 4+.

What I need to do to run in angular 5 ?

**Comment by moayadnajd** [comment]
@muthukumaroptisol  please update to latest and use this syntax in register 

```
import { registerElement } from 'nativescript-angular/element-registry';
import { FilterSelect } from 'nativescript-filter-select';
registerElement('FilterSelect', () => FilterSelect);
```

please don't forget  to let me know if there anything else and star the plugin ⭐️

**Comment by moayadnajd** [comment]
see this example with angular 5 
https://play.nativescript.org/?template=play-ng&id=m8AkhL&v=8
