### ISSUE TITLE
Add enabled property

### ISSUE THREAD

**Issue by PeterStaev** [moayadnajd/nativescript-filter-select#45]
Add handling for `enabled` property that will allow to disable widget if needed.

**Comment by moayadnajd** [comment]
sorry for delay 

I can't understand what you try to say

**Comment by PeterStaev** [comment]
The idea is to have some way to disable the control, so that when the user taps on it nothing happens.

**Comment by OPADA-Eng** [comment]
there is an option called: "disabled" see ReadMe.md for more details

**Comment by PeterStaev** [comment]
First of all sorry for the delayed response, but I just had time to try this and indeed the `disabled` property works as expected 😅 Should have read the manual more thoroughly! Thanks @OPADA-Eng !
