### ISSUE TITLE
Problem when render is set to drop and multiple false

### ISSUE THREAD

**Issue by coderscoven** [moayadnajd/nativescript-filter-select#50]
As the title suggests, when i select an item and realize that it is the wrong one, i can not select another item to over write the wrong one. It requires me to first clear the wrong one and then select again.

**Comment by moayadnajd** [comment]
@coderscoven  you suggest that you can tap again to select another one ?

**Comment by coderscoven** [comment]
No problem, i will just use it like that. Thanks
