### ISSUE TITLE
Support Nativescript-Vue??

### ISSUE THREAD

**Issue by fabioaraujo121** [moayadnajd/nativescript-filter-select#58]
I've addedd the plugin but I can't register to use it with Nativescript-Vue. Does this lib supports it? Anybody knows any similar lib if it doesn't support?

**Comment by gabrielsmelo** [comment]
Yes, despite developer needs to discover by itself how to use all the functionalities. I'm using it myself.

Vue is just a Wrapper around NativeScript Core. Said that, be sure that you can use all the plugins available in NS Market.

Probably to make it work, just add this line to your **app.js** file:

`Vue.registerElement("FilterSelect", () => require("nativescript-filter-select").FilterSelect);`

Then you can use the component normally inside your Vue components.
