### ISSUE TITLE
How to send data variable selectedArray in model to controller ?

### ISSUE THREAD

**Issue by dyazincahya** [moayadnajd/nativescript-filter-select#7]
I have this code in model
`public onSelect(selectedArray,slef) {
console.log('selected array is => ' + JSON.stringify(selectedArray));
console.log('selected array is => ' + JSON.stringify(slef.selected));
}`

my problem is How to send data variable `selectedArray` in **model** to **controller** ?

**Comment by moayadnajd** [comment]
@dyazincahya can you provide more information or share a sample repo with me so i can help

**Comment by moayadnajd** [comment]
@dyazincahya  i just added angular support please see the demo and feel free to open new issue
